FROM scratch
ADD rootfs-amd64-ubuntu-noble.tar.zst /

# Install required packages
RUN apt update && apt upgrade -y
RUN DEBIAN_FRONTEND=noninteractive apt install -y build-essential

# ssh
RUN ssh-keygen -A
RUN mkdir -p /run/sshd

# ros2
RUN useradd -m -U -G adm,sudo -s /bin/zsh kzl
RUN echo "kzl:password" | chpasswd
USER kzl
WORKDIR /home/kzl
RUN mkdir -p /home/kzl/LFS
RUN mkdir -p /home/kzl/Projects/ros2_ws

#
EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]

# Build the image
# docker build --no-cache -t jazzy:init -f Containerfile .

# Run the container in interactive mode
# docker run -i -t --rm -u root -p 2222:22 --name jazzy -h JAZZY <REPOSITORY:TAG> /bin/bash

# Run the container in detached mode
# docker run -d --rm -u root -p 2222:22 --name jazzy -h JAZZY <REPOSITORY:TAG>
# docker run -d --rm -u root -p 2222:22 --name jazzy -h JAZZY --mount type=bind,source=/home/kzl/LFS,target=/home/kzl/LFS --mount type=bind,source=/home/kzl/Projects/ros2_ws,target=/home/kzl/Projects/ros2_ws <REPOSITORY:TAG>
